.TH "Répertoire de référence de tests/gendatas" 3 "Vendredi 24 Avril 2020" "Version 1" "GSBfrais" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de tests/gendatas
.SH SYNOPSIS
.br
.PP
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBfonctions\&.php\fP"
.br
.ti -1c
.RI "fichier \fBmajGSB\&.php\fP"
.br
.in -1c
