.TH "Répertoire de référence de controleurs" 3 "Vendredi 24 Avril 2020" "Version 1" "GSBfrais" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de controleurs
.SH SYNOPSIS
.br
.PP
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBc_accueil\&.php\fP"
.br
.ti -1c
.RI "fichier \fBc_connexion\&.php\fP"
.br
.ti -1c
.RI "fichier \fBc_deconnexion\&.php\fP"
.br
.ti -1c
.RI "fichier \fBc_etatFrais\&.php\fP"
.br
.ti -1c
.RI "fichier \fBc_gererFrais\&.php\fP"
.br
.ti -1c
.RI "fichier \fBc_suiviePaiement\&.php\fP"
.br
.ti -1c
.RI "fichier \fBc_validerUnFrais\&.php\fP"
.br
.in -1c
