.TH "controleurs/c_accueil.php" 3 "Vendredi 24 Avril 2020" "Version 1" "GSBfrais" \" -*- nroff -*-
.ad l
.nh
.SH NAME
controleurs/c_accueil.php
.SH SYNOPSIS
.br
.PP
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI " \fBGSB\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$viisiteurConnecter\fP = \fBestVisiteurConnecter\fP()"
.br
.ti -1c
.RI "\fB$comptableConnecter\fP = \fBestComptableConnecter\fP()"
.br
.ti -1c
.RI "if($viisiteurConnecter) elseif($comptableConnecter) \fBelse\fP"
.br
.in -1c
.SH "Documentation des variables"
.PP 
.SS "$comptableConnecter = \fBestComptableConnecter\fP()"

.SS "$viisiteurConnecter = \fBestVisiteurConnecter\fP()"

.SS "if ( $viisiteurConnecter) elseif ( $comptableConnecter) else"
\fBValeur initiale :\fP
.PP
.nf
{
    include 'vues/v_connexion\&.php'
.fi
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour GSBfrais à partir du code source\&.
