.TH "controleurs/c_validerUnFrais.php" 3 "Vendredi 24 Avril 2020" "Version 1" "GSBfrais" \" -*- nroff -*-
.ad l
.nh
.SH NAME
controleurs/c_validerUnFrais.php
.SH SYNOPSIS
.br
.PP
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI " \fBGSB\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$action\fP = filter_input(INPUT_GET, 'action', FILTER_SANITIZE_STRING)"
.br
.in -1c
.SH "Documentation des variables"
.PP 
.SS "$action = filter_input(INPUT_GET, 'action', FILTER_SANITIZE_STRING)"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour GSBfrais à partir du code source\&.
