.TH "includes/class.pdogsb.inc.php" 3 "Vendredi 24 Avril 2020" "Version 1" "GSBfrais" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/class.pdogsb.inc.php
.SH SYNOPSIS
.br
.PP
.SS "Structures de données"

.in +1c
.ti -1c
.RI "class \fBPdoGsb\fP"
.br
.in -1c
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI " \fBGSB\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour GSBfrais à partir du code source\&.
