.TH "tests/gendatas/majGSB.php" 3 "Vendredi 24 Avril 2020" "Version 1" "GSBfrais" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/gendatas/majGSB.php
.SH SYNOPSIS
.br
.PP
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI " \fBGSB\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$moisDebut\fP = '201609'"
.br
.ti -1c
.RI "\fB$pdo\fP = new PDO('mysql:host=localhost;dbname=gsb_frais', 'root', '')"
.br
.in -1c
.SH "Documentation des variables"
.PP 
.SS "$moisDebut = '201609'"

.SS "$pdo = new PDO('mysql:host=localhost;dbname=gsb_frais', 'root', '')"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour GSBfrais à partir du code source\&.
